spring:
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Flyway migration
  flyway:
    enabled: true
    validate-on-migrate: false
    baseline-on-migrate: true

  # Email Configuration (API MODE - No SMTP)
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD} # This will be the Brevo API KEY

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: OFF

app:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration-ms: 900000
    refresh-expiration-ms: 2592000000
  frontend-url: ${FRONTEND_URL:https://fotori.vercel.app}
  backend-url: ${BACKEND_URL:https://fotori-production.up.railway.app/api}

vietqr:
  account-no: 0944870316
  account-name: FOTORI COMPANY
  acq-id: 970422