spring:
  application:
    name: fotori
  profiles:
    active: test

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
server:
  port: 8082

app:
  jwt:
    secret: test-secret
    access-expiration-ms: 900000
    refresh-expiration-ms: 2592000000
vietqr:
  account-no: 0944870316
  account-name: FOTORI COMPANY
  acq-id: 970422