spring:
  application:
    name: fotori
  profiles:
    active: local

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
server:
  port: ${PORT:8080}

app:
  jwt:
    access-expiration-ms: 900000
    refresh-expiration-ms: 2592000000
  frontend-url: ${FRONTEND_URL:https://fotori.vercel.app}
  backend-url: ${BACKEND_URL:https://fotori-production-87a3.up.railway.app/api}
vietqr:
  account-no: 1024111040
  account-name: FOTORI COMPANY
  acq-id: 970436